export const CHANGE_FEATURE_TITLE = 'CHANGE_FEATURE_TITLE'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ME = 'ME'
export const CREATE_POST = 'CREATE_POST'
export const READ_POST = 'READ_POST'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'